[package]
name = "deezer_downloader"
version = "0.1.0"
edition = "2021"
authors = ["zggff<gigamaximwachau@gmail.com>", "ElMoustacho"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ElMoustacho/deezer_downloader"
readme = "README.md"
keywords = ["deezer", "downloader"]
description = "crate to download music from deezer"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "cookies"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
md5 = "0.7.0"
hex = "0.4.3"
hex-literal = "0.4.1"
block-modes = "0.8.1"
blowfish = "0.8.0"
id3 = "1.14.0"
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
log = "0.4.22"
deezer = "0.1.0"
